export const categories = [
	{ name: 'Pizzas' },
	{ name: 'Breakfast' },
	{ name: 'Snacks' },
	{ name: 'Cocktails' },
	{ name: 'Drinks' },
];

export const ingredients = [
	{ name: 'Cheese Crust', price: 179, imageUrl: '/assets/products/ingredient1.webp' },
	{ name: 'Creamy Mozzarella', price: 79, imageUrl: '/assets/products/ingredient2.webp' },
	{ name: 'Cheddar and Parmesan Cheeses', price: 79, imageUrl: '/assets/products/ingredient3.webp' },
	{ name: 'Spicy Jalapeño', price: 59, imageUrl: '/assets/products/ingredient4.webp' },
	{ name: 'Tender Chicken', price: 79, imageUrl: '/assets/products/ingredient5.webp' },
	{ name: 'Mushrooms', price: 59, imageUrl: '/assets/products/ingredient6.webp' },
	{ name: 'Ham', price: 79, imageUrl: '/assets/products/ingredient7.webp' },
	{ name: 'Spicy Pepperoni', price: 79, imageUrl: '/assets/products/ingredient8.webp' },
	{ name: 'Spicy Chorizo', price: 79, imageUrl: '/assets/products/ingredient9.webp' },
	{ name: 'Pickles', price: 59, imageUrl: '/assets/products/ingredient10.webp' },
	{ name: 'Fresh Tomatoes', price: 59, imageUrl: '/assets/products/ingredient11.webp' },
	{ name: 'Red Onion', price: 59, imageUrl: '/assets/products/ingredient12.webp' },
	{ name: 'Juicy Pineapples', price: 59, imageUrl: '/assets/products/ingredient13.webp' },
	{ name: 'Italian Herbs', price: 39, imageUrl: '/assets/products/ingredient14.webp' },
	{ name: 'Sweet Pepper', price: 59, imageUrl: '/assets/products/ingredient15.webp' },
	{ name: 'Feta Cubes', price: 79, imageUrl: '/assets/products/ingredient16.webp' },
	{ name: 'Meatballs', price: 79, imageUrl: '/assets/products/ingredient17.webp' },
].map((obj, index) => ({ id: index + 1, ...obj }));

export const products = [
	{ name: 'Omelet with Ham and Mushrooms', imageUrl: '/assets/products/product1.webp', categoryId: 2 },
	{ name: 'Omelet with Pepperoni', imageUrl: '/assets/products/product2.webp', categoryId: 2 },
	{ name: 'Coffee Latte', imageUrl: '/assets/products/product3.webp', categoryId: 2 },
	{ name: 'Denwich Ham and Cheese', imageUrl: '/assets/products/product4.webp', categoryId: 3 },
	{ name: 'Chicken Nuggets', imageUrl: '/assets/products/product5.webp', categoryId: 3 },
	{ name: 'Baked Potatoes with Sauce 🌱', imageUrl: '/assets/products/product6.webp', categoryId: 3 },
	{ name: 'Dodster', imageUrl: '/assets/products/product7.webp', categoryId: 3 },
	{ name: 'Spicy Dodster 🌶️🌶️', imageUrl: '/assets/products/product8.webp', categoryId: 3 },
	{ name: 'Banana Milkshake', imageUrl: '/assets/products/product9.webp', categoryId: 4 },
	{ name: 'Caramel Apple Milkshake', imageUrl: '/assets/products/product10.webp', categoryId: 4 },
	{ name: 'Oreo Cookie Milkshake', imageUrl: '/assets/products/product11.webp', categoryId: 4 },
	{ name: 'Classic Milkshake 👶', imageUrl: '/assets/products/product12.webp', categoryId: 4 },
	{ name: 'Irish Cappuccino', imageUrl: '/assets/products/product13.webp', categoryId: 5 },
	{ name: 'Caramel Cappuccino', imageUrl: '/assets/products/product14.webp', categoryId: 5 },
	{ name: 'Coconut Latte', imageUrl: '/assets/products/product15.webp', categoryId: 5 },
	{ name: 'Americano Coffee', imageUrl: '/assets/products/product16.webp', categoryId: 5 },
	{ name: 'Coffee Latte', imageUrl: '/assets/products/product17.webp', categoryId: 5 },
];